### ISSUE TITLE
很牛逼啊，请支持编码下载，还有使用文档

### ISSUE THREAD

**Issue by Akimotorakiyu** [sdoyuxing/VideoRecording#1]
支持编码下载，还有使用文档

**Comment by sdoyuxing** [comment]
你的是意思是支持指定媒体格式的下载么

**Comment by sdoyuxing** [comment]
其他媒体格式之前也在想弄，但是有点难度，本来想是想弄不支持webRTC的浏览器的视频录制的。最近有点忙就中断了，有兴趣的话一起学习下呀

**Comment by Akimotorakiyu** [comment]
看了下代码，看明白实现了。

**Comment by sdoyuxing** [comment]
你怎么发现我这个插件的呢？有没有兴趣一起维护呢？

**Comment by Akimotorakiyu** [comment]
有些视频下载不了，就想着直接录下来得了，发现各种插件要么收费、要么下载不下来，就在github 上找到你这个了

**Comment by Akimotorakiyu** [comment]
维护好呀，这个是什么发展方向呢？

**Comment by sdoyuxing** [comment]
就扩展组件，其实国外有个插件专门用webRTC做页面的各种视频录制的，我也是看那个插件的源码写的这个，这个视频在谷歌浏览器上只支持webm

**Comment by sdoyuxing** [comment]
那个库名字叫RecordRTC，你可以去看看，里面很多视频相关的功能

**Comment by Akimotorakiyu** [comment]
RecordRTC 我以前看过

**Comment by sdoyuxing** [comment]
厉害了
